title: LZH_photography
url: https://github.com/lzhzlw/photo/
baseurl: 

author: Disha Patel
description: Discovering the world with my vision.

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  2024_chicago:
    output: true
  beijing:
    output: true
  on_the_way:
    output: true 
  linzhi:
    output: true
  yangzhou:
    output: true
  us:
    output: true

markdown: kramdown
kramdown:
  input: GFM
